name: Test

on:
  push:
    branches: [ 'master', 'release-*' ]
  pull_request:
    branches: [ 'master', 'release-*' ]

jobs:
  build-presubmit:
    name: Go Build Test
    strategy:
      matrix:
        go-version: [1.15.x]
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}

    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code onto GOPATH
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ./src/github.com/tom24d/eventing-dockerhub

      - name: Run Go vet
        run: go vet ./...

      - name: Run Build Test
        run: go build -race ./...
